services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=${FLASK_ENV:-production}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./instance:/app/instance
    container_name: ${CONTAINER_NAME:-my_container}
    restart: on-failure

networks:
  default:
    name: ${NETWORK_NAME:-my_network}
    external: true
